"""empty message

Revision ID: 62a6b4bfd13
Revises: None
Create Date: 2016-12-02 14:24:47.564000

"""

# revision identifiers, used by Alembic.
revision = '62a6b4bfd13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('T_done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    ### end Alembic commands ###
